version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dummy
      MYSQL_USER: dummy
      MYSQL_PASSWORD: dummy
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      cube-network:
        ipv4_address: 192.168.2.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    networks:
      cube-network:
        ipv4_address: 192.168.2.3

  redis:
    image: redis:6.2.5
    command: redis-server --requirepass "$REDIS_PASSWORD"
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: redispasswd
    networks:
      cube-network:
        ipv4_address: 192.168.2.4

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
    networks:
      cube-network:
        ipv4_address: 192.168.2.5

volumes:
  dbdata:
  redis:
  redis-config:

networks:
  cube-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/29
          gateway: 192.168.2.1